name: CustomItems
main: me.boykev.cit.Main
author: boykev
website: https://www.boykevanvugt.nl
version: 2.2BETA
api-version: 1.12
api: "1.12"
depend: [NBTAPI]
commands:
  nbt:
    description: Debug commando.
  mtgive:
    description: Geef jezelf een item met een mtcustom tag.
  gcitems:
    description: Krijg de lijst met custom items of voeg een item toe.
  customitems:
    description: Informatie over de plugin.