name: CustomItems
main: me.boykev.cit.Main
author: boykev
website: http://www.boykevanvugt.nl
version: 1.0BETA
api-version: 1.12
api: "1.12"
commands:
  testitem:
    description: Tikkie main command.
  setnbt:
    description: Tikkie main command.